name: pokegrading_backend
description: PokéGrading — Backend (Dart + Shelf)
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  # ─── HTTP Server ─────────────────────────────────────────
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5

  # ─── Base de Datos ────────────────────────────────────────
  postgres: ^3.3.2

  # ─── Configuración ────────────────────────────────────────
  dotenv: ^4.2.0

  # ─── Email ───────────────────────────────────────────────
  mailer: ^6.1.0
  http: ^0.13.6

  # ─── Utilidades ──────────────────────────────────────────
  uuid: ^4.4.0
  crypto: ^3.0.3
  logging: ^1.2.0
  file_picker: ^8.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
